project:
  type: website
  output-dir: docs

website:
  title: "Stat 3125 ProjectGuide"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - getting-started.qmd
      - href: example-project-nav.qmd
        text: Examples
  page-footer:
    left: ""
    center: "Built with Quarto"
    right:  ""
      #- icon: github
        #href: https://github.com


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true